name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 3.0.0
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: "^3.0.0"

dependencies:
  archive: ^4.0.7
  xml: ^6.6.1

dev_dependencies:
  path: ^1.9.1
  lints: ^6.0.0
  test: ^1.26.3
